export default [ { id: 1,
  type: 'face',
  fileName: 'face-1',
  tag: [ 'boy', 'girl' ] },
{ id: 2,
  type: 'face',
  fileName: 'face-2',
  tag: [ 'boy', 'girl' ] },
{ id: 3,
  type: 'face',
  fileName: 'face-3',
  tag: [ 'boy', 'girl' ] },
{ id: 4,
  type: 'face',
  fileName: 'face-4',
  tag: [ 'boy', 'girl' ] },
{ id: 5,
  type: 'hair',
  fileName: 'hair-11',
  tag: [ 'boy', 'girl' ] },
{ id: 6, type: 'eye',
  fileName: 'eye-21',
  tag: [ 'boy', 'girl' ] },
{ id: 7,
  type: 'eyebrows',
  fileName: 'eyebrows-16',
  tag: [ 'boy', 'girl' ] },
{ id: 8,
  type: 'mouth',
  fileName: 'mouth-31',
  tag: [ 'boy', 'girl' ] },
{ id: 9,
  type: 'nose',
  fileName: 'nose-26',
  tag: [ 'boy', 'girl' ] },
{ id: 10,
  type: 'wear',
  fileName: 'wear-6',
  tag: [ 'boy', 'girl' ] } ]